### ISSUE TITLE
Console input

### ISSUE THREAD

**Issue by JakobRinke** [JeffaloBob/kahoot-gui#21]
Can you make that I can use the console to give the Input instead of a window.

I want to host this on my server.

**Comment by jeffalo** [comment]
could you please clarify?

what do you mean by server?

**Comment by JakobRinke** [comment]
what I want to do is, to control the program from my python program, so I can automate the program

**Comment by jeffalo** [comment]
I don't think that this would be the thing you want to use. This is a front end for a nodejs package called kahoot.js-updated. I would suggest looking into that.

About the python, I'm not sure.
