### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by jeffalo** [JeffaloBob/kahoot-gui#5]
Now that the project is getting slightly bigger, the code is getting messier and messier.

A code cleanup is really needed badly.

- [x] Comment big parts of the code

- [x] Keep a consistent variable naming scheme

- [x] Remove unused, and redundant variables

- [x] Fix formatting

**Comment by Odisseuss** [comment]
Hi @JeffaloBob , I would be glad to help you out

**Comment by jeffalo** [comment]
@Odisseuss thanks! i think the most important part to clean up is variable naming.

**Comment by Odisseuss** [comment]
@JeffaloBob my pleasure! Yup, i will take that into account.

**Comment by Odisseuss** [comment]
@JeffaloBob From what I see, mainly the yeeter.js file is the one with problems, right?

**Comment by jeffalo** [comment]
@Odisseuss Yes. That is the main script and it's pretty messy 

also may I ask where you found this project? (just wanted to know for future reference)

**Comment by Odisseuss** [comment]
@JeffaloBob I don't remember exactly. Either i searched on google for a github issues help_wanted bot, or i searched directly in github for help_wanted.

**Comment by jeffalo** [comment]
@Odisseuss that's cool. now thinking about it, the script is pretty clean. Mabye if you want you could help with another issue?

You can still try cleaning it up more if you want. :smiley:

**Comment by Odisseuss** [comment]
@JeffaloBob 
Uhm.. can i take this again? :D

**Comment by jeffalo** [comment]
@Odisseuss That's completely fine with me :D
