### ISSUE TITLE
name choices

### ISSUE THREAD

**Issue by jeffalo** [JeffaloBob/kahoot-gui#7]
**Is your feature request related to a problem? Please describe.**
people might be using anti bots/kahoot might add one.

**Describe the solution you'd like**
allow users to create a name list bots choose names from as apposed to [prefix]+[number]

and while we're at it allow users to choose if name is the prefix/suffic [number]+[suffix]

**Describe alternatives you've considered**
not

**Additional context**

**Comment by Odisseuss** [comment]
Can i claim this issue as well? If yes, let me clarify something. So, the user should be allowed to choose from the 3 bot naming options currenltly present in the Advanced Settings section right? Also, what do you mean more exactly by [prefix]+[number] and [number] + [suffix]?

**Comment by jeffalo** [comment]
Yes you may claim this issue, @Odisseuss . The 3 naming options in the advanced settings currently do nothing, so this for making the name choices work.

[prefix] and [suffix] is just what people would be entering in the name field. (this one)
![image](https://user-images.githubusercontent.com/40470736/73370549-afd8f800-42b4-11ea-80dd-40a30e53b031.png)

and [number] is the number that gets added on to that for each bot. eg.
![image](https://user-images.githubusercontent.com/40470736/73370704-eca4ef00-42b4-11ea-8125-4be1096a1d86.png)

Currently it only does prefix+number so number+suffix is essentially that reversed.

As for choosing names I was thinking that 
![image](https://user-images.githubusercontent.com/40470736/73370880-3097f400-42b5-11ea-9964-93670943954f.png)
could allow the user to input a bunch of names that the bots would use instead of the [prefix]+number and number+[suffix]

I guess some parts of the joining form would have to be disabled when the name list option is chosen. 

eg.
![image](https://user-images.githubusercontent.com/40470736/73371107-81a7e800-42b5-11ea-849f-44b9db56bbe4.png)

**Comment by Odisseuss** [comment]
Ok, got it. I will start working on it. Again, please commit often so i can have the latest changes so no more conflicts will emerge.

**Comment by jeffalo** [comment]
@Odisseuss yep, I always commit and keep this repo up-to-date when I can. Thank you so much for your help.

**Comment by Odisseuss** [comment]
@JeffaloBob Happy to help!

**Comment by jeffalo** [comment]
@Odisseuss Thanks so much :)

**Comment by Odisseuss** [comment]
@JeffaloBob  I think you can close this issue now. :D
